version: '3'
services:
  app:
    container_name: my-node-app
    build: .
    ports:
      - '5800:5800'
    depends_on:
      -db
  mongo:
    container_name: mongo
    image: mongo:5
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'      